### ISSUE TITLE
After partitioning, How to get training dataset and some errors within training encountered.

### ISSUE THREAD

**Issue by tangbogreat** [saareliad/FTPipe#6]
1. exec: python -m pipe.data.download_glue_data,
  will encounter some errors such as: 400 HTTP error. I reviewed the code such as: 
TASK2PATH = {"CoLA":'https://firebasestorage.googleapis.com/v0/b/mtl-sentence-representations.appspot.com/o/data%2FCoLA.zip?alt=media&token=46d5e637-3411-4188-bc44-5809b5bfb5f4'}, the url is really wrong.

2. Can you provide more detailed Readme about training including training dataset.

**Comment by saareliad** [comment]
Anyway, until I'll extend the readme, 
For t5 experiments, TensorFlow datasets (tfds) were used.
This is the most convenient way and I suggest focusing on it.
for example https://github.com/saareliad/FTPipe/blob/afdd20dad8119e8cf6b49c5eb0accbe13153fd91/t5_used_scripts_example/run_experiments.sh#L24-L27
this happens using `--mode preprocess`

tfds dataset is defined here https://github.com/saareliad/FTPipe/blob/afdd20dad8119e8cf6b49c5eb0accbe13153fd91/pipe/data/t5/t5_tfds.py

Note that sometimes the dataset/dataloader is also partitioned to be efficient in the pipeline (e.g., dataloader in the last stage loads labels; data loader in the first stage does not) . You can explore code from here https://github.com/saareliad/FTPipe/blob/afdd20dad8119e8cf6b49c5eb0accbe13153fd91/pipe/main.py#L480

**Comment by tangbogreat** [comment]
Thank you. According to your reply, I ran the training part again and encountered the following exceptions: 
`mpirun --allow-run-as-root -n 1 python3 -m pipe.main --config pipe/configs/t5/new_t5_exp/mpipe/multirc/stale_layer_graph.json --seed 42

2022-06-17 15:53:17.465888: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Using 5 Threads
Running in distributed mode
[W Context.cpp:70] Warning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (function operator())
Loading partitioned model and dataset...
/usr/local/python/lib/python3.8/site-packages/apex/pyprof/__init__.py:5: FutureWarning: pyprof will be removed by the end of June, 2022
  warnings.warn("pyprof will be removed by the end of June, 2022", FutureWarning)
/data/ftpipe/FTPipe-master/pipe/configs/parse_json_config.py:37: UserWarning: Config path changed by child
  warnings.warn("Config path changed by child")
Initialized process group; backend: mpi, rank: 0, local_rank: 0, world_size: 1
{'missing_keys': ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight', 'lm_head.weight'], 'error_msgs': []}
/usr/local/python/lib/python3.8/site-packages/transformers/models/t5/tokenization_t5.py:163: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on t5-3b automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/python/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/ftpipe/FTPipe-master/pipe/main.py", line 532, in <module>
    start()
  File "/data/ftpipe/FTPipe-master/pipe/main.py", line 528, in start
    start_distributed(python_args_dict=python_args_dict)
  File "/data/ftpipe/FTPipe-master/pipe/main.py", line 375, in start_distributed
    main(args)
  File "/data/ftpipe/FTPipe-master/pipe/main.py", line 427, in main
    samplers) = prepare_pipeline(args, shared_ctx=shared_ctx)
  File "/data/ftpipe/FTPipe-master/pipe/prepare_pipeline.py", line 525, in prepare_pipeline
    parsed_config.load_model(handler=handler, bs_train=args.bs_train, rank=args.rank)
  File "/data/ftpipe/FTPipe-master/pipe/models/parse_config.py", line 130, in load_model
    model = handler.realize_stage_for_rank(batch_size=bs_train, my_rank=rank)
  File "/data/ftpipe/FTPipe-master/pipe/models/registery/model_handler.py", line 62, in realize_stage_for_rank
    return pipe_config.realize_stage_for_rank(layers, tensors, batch_size, my_rank)
  File "/data/ftpipe/FTPipe-master/pipe/models/simple_partitioning_config.py", line 88, in realize_stage_for_rank
    return self.realize_stage(layers, tensors, stage_id, device=device)
  File "/data/ftpipe/FTPipe-master/pipe/models/simple_partitioning_config.py", line 94, in realize_stage
    return stage_cls(layers, tensors, device=device)
  File "/data/ftpipe/FTPipe-master/models/partitioned/t5_3b_tied_lmheads_512_4_8p_bw12_async_squad1_mpipe.py", line 522, in __init__
    self.add_module(f'l_{idx}' ,layers[layer_scope])
KeyError: 'T5ForConditionalGeneration/T5Stack[encoder]/ModuleList[block]/T5Block[0]/ModuleList[layer]/T5LayerSelfAttention[0]/T5LayerNorm[layer_norm]'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[51390,1],0]
  Exit code:    1
`

I don't know why I made this mistake. I'm looking forward to your reply

**Comment by saareliad** [comment]
I have noticed that you are running mpi with -n 1, the config shall run with -n 16

see
https://github.com/saareliad/FTPipe/blob/master/models/partitioned/t5_3b_tied_lmheads_512_4_8p_bw12_async_squad1_mpipe.py
it is for 16 processes per node, for a node with 8 GPUs

**Comment by saareliad** [comment]
I am closing this. To summarize, after partitioning - handling of the training dataset can be done automatically, as was done in latest experiments
https://github.com/saareliad/FTPipe/blob/afdd20dad8119e8cf6b49c5eb0accbe13153fd91/t5_used_scripts_example/run_experiments.sh#L24-L27
